### ISSUE TITLE
unpickling error when doing the "simple example"

### ISSUE THREAD

**Issue by zingale** [abatten/fruitbat#29]
When I run the "simple example" here:

https://fruitbat.readthedocs.io/en/latest/user_guide/getting_started.html#simple-example

I get an `UnpicklingError`:

```
FRB180110.calc_redshift(method="Zhang2018", cosmology="Planck18")                                                                        
---------------------------------------------------------------------------
UnpicklingError                           Traceback (most recent call last)
/usr/lib64/python3.7/site-packages/numpy/lib/npyio.py in load(file, mmap_mode, allow_pickle, fix_imports, encoding)
    439             try:
--> 440                 return pickle.load(fid, **pickle_kwargs)
    441             except Exception:

UnpicklingError: invalid load key, 'v'.

During handling of the above exception, another exception occurred:

OSError                                   Traceback (most recent call last)
<ipython-input-5-9a85f326ef82> in <module>
----> 1 FRB180110.calc_redshift(method="Zhang2018", cosmology="Planck18")

~/.local/lib/python3.7/site-packages/fruitbat/_frb.py in calc_redshift(self, method, cosmology, subtract_host, lookup_table)
    306                 table_name = "".join(["custom_", method, ".npz"])
    307 
--> 308             lookup_table = table.load(table_name)
    309 
    310         self.z = table.get_z_from_table(input_dm, lookup_table)

~/.local/lib/python3.7/site-packages/fruitbat/table.py in load(name, data_dir)
    138 
    139     filename = os.path.join(data_dir, name)
--> 140     return np.load(filename)
    141 
    142 

/usr/lib64/python3.7/site-packages/numpy/lib/npyio.py in load(file, mmap_mode, allow_pickle, fix_imports, encoding)
    441             except Exception:
    442                 raise IOError(
--> 443                     "Failed to interpret file %s as a pickle" % repr(file))
    444     finally:
    445         if own_fid:

OSError: Failed to interpret file '/home/zingale/.local/lib/python3.7/site-packages/fruitbat/data/Zhang2018_Planck18.npz' as a pickle
```

I am using python 3.7.3

**Comment by abatten** [comment]
Hi @zingale, I just tested it with python 3.7.3, and I can't seem to replicate your issue. This might be an issue with the version of `numpy`. Are you able to tell me which version of `numpy` you are using?

Also, did you install `fruitbat` using `pip` or by cloning the master branch?

**Comment by zingale** [comment]
I'm running numpy 1.15.4

playing around some more, things work if I install the package via:
```
pip3 install fruitbat --user
```
but I get the above failures if I install from source, as:
```
git clone https://github.com/abatten/fruitbat
cd fruitbat/
pip3 install . --user
```
so maybe there is a step missing in the latter install method?

**Comment by abatten** [comment]
After testing this for a long time I think I have worked out the issue. It appears that you do not have git-lfs installed.

The data files for `fruitbat` are saved in .npz format and are stored using the git Large File Storage. So when you clone the directory and install it, if you don't have git-lfs installed python doesn't know how to extract the data.

I'll add some documentation to the README and the online docs listing this a a requirement if you want to install from source, and links describing the process.

There is a wiki on installing git-lfs depending on your OS. https://github.com/git-lfs/git-lfs/wiki/Installation It's easily install using homebrew (macOS) or apt-get (debian).

You may/may not have to clone the directory again.

**Comment by zingale** [comment]
thanks.  I will try this out later today.

**Comment by abatten** [comment]
The documentation for installing git-lfs has been added in #33.
