### ISSUE TITLE
Expected FRB designation (`name`)

### ISSUE THREAD

**Issue by 0xCoto** [abatten/fruitbat#42]
Does [`fruitbat.Frb`](https://fruitbat.readthedocs.io/en/latest/api/fruitbat.Frb.html) support the more up-to-date TNS designation for the `name` parameter (e.g. `FRB 20180110`) or only the older-ish one (e.g. `FRB180110`)? If not, it might be worth adding a simple automatic parser between the two designation to support both 'standards'. Otherwise, I can simply do the parsing before passing it to `fruitbat.Frb()`.

**Comment by 0xCoto** [comment]
Actually, I think I misunderstood:

> It’s also possible to ‘name’ the FRB using the keyword name, which can be useful when calculating redshifts of many FRBs at once.

My goal is to compute the redshift for a list of FRBs, provided their galactic coordinates and DMs. Is this `name` parameter optional for more convenient handling of data, or does it have a different purpose?

**Comment by abatten** [comment]
Hi, yes the name parameter is optional. If you are computing the redshift of a list of DMs, you definitely don't need the name as well. It was added just in case some future feature would need the name of the FRB (i.e. outputting the FRB object to JSON). It's also completely arbitrary what name you give it so `FRB20180110` is completely valid and so is `MyFavouriteFRB`.

**Comment by abatten** [comment]
I'm going to close this now, since it seems resolved.
