### ISSUE TITLE
Redshift cross-check/verification

### ISSUE THREAD

**Issue by 0xCoto** [abatten/fruitbat#49]
I have built a [script](https://github.com/HeRTA/FRBSTATS/blob/main/redshifts.py#L61-L69) to compute the redshift for all FRBs using fruitbat, based on the burst's galactic coordinates and DM. I am trying to verify the estimated redshift is about right and I haven't messed anything up with the code. Is there perhaps some catalogue I could refer to, to cross-check my derived redshifts?

E.g., for `FRB 20190214A` (arbitrary selection) with:
```py
l=148.5
b=22.03
DM=498.2
```
I get a redshift of `z=1.215`. Does this look right?

**Comment by abatten** [comment]
Hi @0xCoto, sorry for the delay. I've been quite sick.

That redshift does sound a little high for a DM~500. When I calculate the redshift, I get around 0.44. Even with different galactic DM models. I have included my code below.

If you want to send some of your code, I could look at it and see where we differ and what's causing the difference in the result.

```
In [1]: import fruitbat

In [2]: frb = fruitbat.Frb(498.2, gl=148.5, gb=22.03)

In [3]: frb.calc_dm_galaxy("ymw16")
Out[3]: <Quantity 76.52399445 pc / cm3>

In [4]: frb.calc_redshift(method="Batten2021")
Out[4]: <Quantity 0.44305183>

In [5]: frb.calc_dm_galaxy("ne2001")
Out[5]: <Quantity 69.73789215 pc / cm3>

In [6]: frb.calc_redshift(method="Batten2021")
Out[6]: <Quantity 0.44951424>
```

**Comment by 0xCoto** [comment]
@abatten No worries at all, get well soon!

I ended up figuring out what the issue was. Apparently I had some misalignment issues with the arrays I was processing, so I ended up mixing up some values with different FRBs.

Indeed, I get a value of 0.4431, so everything looks good.
